name: CI

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Upload node_modules
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: node_modules/
          retention-days: 1

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules/

      - name: Fix executable permissions
        run: |
          chmod -R +x node_modules/.bin 2>/dev/null || true
          ls -la node_modules/.bin || echo "No .bin directory found"
          echo "PATH environment: $PATH"
          # NPXを使用して実行する
          npx --no-install next --version || echo "Unable to run next via npx"

      - name: Lint
        run: npx --no-install next lint

  type-check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules/

      - name: Fix executable permissions
        run: chmod -R +x node_modules/.bin 2>/dev/null || true

      - name: Type check
        run: npx --no-install tsc --noEmit

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules/

      - name: Fix executable permissions
        run: chmod -R +x node_modules/.bin 2>/dev/null || true

      - name: Run tests
        run: npx --no-install jest
